server:
  port: 8080
spring:
  application:
    name: grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9999'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
